### ISSUE TITLE
ERR

### ISSUE THREAD

**Issue by deflationz** [DoppelKorn/Youtube-Viewer#2]
Getting the error below when trying to use, doesn't matter what I do.

Traceback (most recent call last):
  File "c:\Users\Admin\Downloads\Youtube-Viewer-main\Youtube-Viewer-main\viewer.py", line 216, in <module>    
    main()
  File "c:\Users\Admin\Downloads\Youtube-Viewer-main\Youtube-Viewer-main\viewer.py", line 204, in main        
    work = testProxies(getProxyList(countryCode))  # stores working proxies
  File "c:\Users\Admin\Downloads\Youtube-Viewer-main\Youtube-Viewer-main\viewer.py", line 160, in getProxyList
    data = [list(filter(None, i))[0] for i in re.findall('<td class="hm">(.*?)</td>|<td>(.*?)</td>', source)] 
  File "c:\Users\Admin\Downloads\Youtube-Viewer-main\Youtube-Viewer-main\viewer.py", line 160, in <listcomp>  
    data = [list(filter(None, i))[0] for i in re.findall('<td class="hm">(.*?)</td>|<td>(.*?)</td>', source)]
IndexError: list index out of range

**Comment by soerenpriess** [comment]
Hey, that's weird. The code that gives the error just goes through the table on the website and gets all the entries. If you go to free-proxy-list.net and display the html page there, you can see the structure.
![image](https://user-images.githubusercontent.com/56112882/153516771-71df9acd-07cd-471e-bed2-85b8aa555814.png)
In the picture you can see the structure of the table. Your error shows that there is no entry at the current index.
I'll take a closer look at it over the next few days.

**Comment by soerenpriess** [comment]
I did some testing and tested the program on another computer and I think you have a local error. Are you still getting this error?
